### ISSUE TITLE
Feat : 상품추가 기능 구현

### ISSUE THREAD

**Issue by yell2023** [ttodam-ttodam/ttodam-ttodam-BE#10]
## Description
게시글 작성에 상품추가 기능을 추가하고, 삭제 기능 구현.

## Estimated Duration
4/9(화) ~ 4/11 (목) [3일]

## Classification
- [X] 기능
- [ ] 버그
- [ ] 기타

## TO-DO
- [x] 상품 모델 생성
- [x] 상품 추가 기능 구현
- [x] 상품 삭제 기능 구현
