### ISSUE TITLE
Feat : 개인 채팅방 생성 API 구현

### ISSUE THREAD

**Issue by yje9802** [ttodam-ttodam/ttodam-ttodam-BE#2]
## Description
- 유저가 주최자에게 문의할 수 있는 일대일 채팅방 생성 
  - 게시글에서 버튼을 통해 생성이 이루어진다.
  - '모집중' 상태의 게시글만 가능하다.
- `POST`
  - body를 통해 `postId`와 `userId` 전달

## Estimated Duration
연결 구현 : 4/3(화) ~ 4/4 (수) [2일]
채팅방 생성 : 4/10(수) ~ 4/11(목)

## Classification
- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO
- [x] WebSocket 연결 구현
- [x] postId와 userId를 통해 게시글과 유저의 정보 불러오기
- [x] 채팅방 생성과 DB 작업
