### ISSUE TITLE
Refactor :  게시글 CRUD 수정

### ISSUE THREAD

**Issue by yell2023** [ttodam-ttodam/ttodam-ttodam-BE#24]
## Description
게시글 작성/수정 기능의 이미지 부분 수정하고, 전체적으로 유효성 추가, 예외처리 추가

## Estimated Duration
4/17(수) ~ 4/19(금) [3일]

## Classification
- [X] 기능
- [ ] 버그
- [ ] 기타

## TO-DO
- [x] 유저 부분과 연결
- [x] 게시글 작성 기능의 이미지업로드 부분 수정
- [x] 게시글 조회 기능을 유저의 주소 기반으로 변경
- [x] 카테고리별 게시글 조회 기능 구현
- [x] 참여요청 상황을 반영한 모집상태 추가
- [x] 에러코드 추가
