### ISSUE TITLE
Refactor : 게시글, 게시글 조회 수정

### ISSUE THREAD

**Issue by yell2023** [ttodam-ttodam/ttodam-ttodam-BE#59]
## Description
- 게시글 Entity 수정
- 게시글 상세 조회 수정
- 작성한 게시글 조회 추가

## Estimated Duration
4/25(목) ~ 4/26 (금) [2일]

## Classification
- [X] 기능
- [ ] 버그
- [ ] 기타

## TO-DO
- [x] 게시글 Entity 공구상태 추가
- [x] 게시글 공구 상태 변경 로직 추가
- [x] 상세 조회 시, 로그인 유저의 조회 게시글 참여상태 반환
- [x] 작성한 게시글 조회 추가
